apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: hello-o2
spec:
  groups:
    - name: hello-o2.rules
      rules:
        - alert: HelloO2HighRatePerInstanceAlert
          annotations:
            message: |
              High request rate on {{ $labels.instance }}.
          expr: rate(hello_world_server_requests_total{namespace="hello-o2"}[2m]) > 10
          labels:
            severity: warn
        - alert: HelloO2HighRateGlobalAlert
          annotations:
            message: |
              High request rate.
          expr: sum(rate(hello_world_server_requests_total{namespace="hello-o2"}[2m])) > 50
          labels:
            severity: warn
